### ISSUE TITLE
Temas dos grupos

### ISSUE THREAD

**Issue by jemaf** [COLTEC-DAW/Seminarios-Frameworks-CSS#16]
- Input de usuário: buttons e forms **(Enzo Bigodeiro, Luan Vitor, Lucas Gomes, Luiza Moselli)**
- Exibição de conteúdo: tables, panels e wells
- imagens e media: Images, Thumbnails, Media objects **(Bernardo T. , Gabriel R)**
- Alertando usuários: Labels, Badges, Alerts, Progress Bars **(Amanda Bueno, Bernardo Vale, Enzo Praga, Gabriel Moreira)**
- Navegação: Tabs, Pills e Tabbed Navigation
- Hide and Seek: Collapse e Accordion **(Gustavo Augusto, Thiago, Pedro)**
- Revelando conteúdo: Tooltips, Popovers e Toasts
- O Carousel **(Arthur Cordeiro, Eric Catarina, Gabriel Benvindo e Gabriel Machado)**
- Janelas Modal e Cards **(Gustavo Rangel, Jean, Wesley e Daniel)**
 - Barra de navegação: o componente NavBar
 - Autolocalizacão: Scrollspy e Affix

**Comment by Aikenpil** [comment]
Grupo: Gustavo Rangel, Jean, Wesley e Daniel
Janela modal e card

**Comment by gbegnami** [comment]
Tema: O Carousel;
Grupo: Arthur Cordeiro, Eric Catarina, Gabriel Benvindo e Gabriel Machado;

**Comment by gustavoar3** [comment]
Grupo: Gustavo Augusto, Thiago, Pedro, Ulisses
Tema: Hide and Seek: Collapse e Accordion

**Comment by EoBerrr** [comment]
Tema: imagens e media: Images, Thumbnails, Media objects
Grupo: Bernardo T. , Gabriel R.

**Comment by amanda-bueno** [comment]
Grupo: Amanda Bueno, Bernardo Vale, Enzo Praga, Gabriel Moreira
Tema: Alertando usuários: Labels, Badges, Alerts, Progress Bars

**Comment by LuaVitor** [comment]
Grupo:  Enzo Bigodeiro, Luan Vitor, Lucas Gomes, Luiza Moselli
Tema:   Input de usuário: buttons e forms

**Comment by guilherme-dnz** [comment]
Grupo: Guilherme Diniz, Lorrayne Paula, Jhulya Cristina, Letícia Rosa, Hannah Luiza
Tema: Barra de navegação: o componente NavBar

**Comment by deblah** [comment]
Grupo: Wanessa de Oliveira, Isabela Cristina, Waleska, Deborah Kahey
Tema: Exibição de conteúdo: tables, panels e wells

**Comment by fernandrade04** [comment]
Participantes: Eduardo Evangelista, Fernando Andrade, Elder gabriel e João victor
Tema:Barra de navegação: o componente NavBar
