### ISSUE TITLE
Entrega Seminário Frameworks DAW

### ISSUE THREAD

**Issue by arthur-cordeiro** [COLTEC-DAW/Seminarios-Frameworks-CSS#17]
Integrantes: Arthur Cordeiro, Éric Catarina, Gabriel Benvindo e Gabriel Machado.

LINK para o código que também representa os slides em formato de carousel XD:

https://github.com/CORDERIN/DAW---CAROUSEL

**Comment by jemaf** [comment]
* Bom exemplo de uso do carrossel!
* Ótimos slides
* Explicação bem detalhada

Nota: 100%
