### ISSUE TITLE
Trabalho Seminário DAW

### ISSUE THREAD

**Issue by deblah** [COLTEC-DAW/Seminarios-Frameworks-CSS#19]
Exibição de conteúdo: tables, panels e wells
Grupo: Deborah Kahey, Isabela Cristina, Waleska Maria, Wanessa de Oliveira
//repositório git
https://github.com/deblah/DAW-TABLE-PANEL-WELL.git
//link do slide
https://docs.google.com/presentation/d/19vMAfEH93LjbvUxCDITM_83w19KFHkY5aXzSElvTDuw/edit?usp=sharing

**Comment by jemaf** [comment]
* Os exemplos foram bons, mas faltou uma demonstração geral sobre os componentes
* Alguns problemas no decorrer da apresentação

Nota: 0,85

**Comment by deblah** [comment]
?????????????? 0,85
