### ISSUE TITLE
Entrega Seminário Frameworks 

### ISSUE THREAD

**Issue by amanda-bueno** [COLTEC-DAW/Seminarios-Frameworks-CSS#20]
https://www.canva.com/design/DAFA4kW2Etw/zl0_GNmkTn5EKpmbAKqG2w/view?utm_content=DAFA4kW2Etw&utm_campaign=designshare&utm_medium=link&utm_source=publishpresent

**Comment by jemaf** [comment]
+ Ótimos casos de uso
+ Exemplos muito práticos
+ Apresentação bem completa

Nota: 100%
