### ISSUE TITLE
Entrega Seminário Frameworks CSS

### ISSUE THREAD

**Issue by JeanBerl** [COLTEC-DAW/Seminarios-Frameworks-CSS#21]
Código Janela Modal: https://plnkr.co/edit/ec4QIx78SNMot458
Código Card: https://plnkr.co/edit/1Psdpj3R9YhiOnu1?preview
Slides: https://docs.google.com/presentation/d/1tfpKSLCxK7KkvrQTn0XuMNzDJEotOtzKxqMqYaypU1Q/edit#slide=id.g12cd0f86b62_0_14
Grupo: Jean Berly, Gustavo Rangel, Daniel de Miranda, Wesley Figueiredo

**Comment by jemaf** [comment]
* Faltou apresentar um pouco mais de detalhes os componentes (propriedades, subcomponentes, cenários de uso)

Nota: 80%
