### ISSUE TITLE
Seminário Frameworks CSS

### ISSUE THREAD

**Issue by ThiagoL29** [COLTEC-DAW/Seminarios-Frameworks-CSS#22]
Integrantes: Gustavo Augusto, Pedro, Thiago, Ulisses

Slides: https://www.canva.com/design/DAFA4pn7DEk/RHOdrlw6pqRG8-KXJTlvJg/view?utm_content=DAFA4pn7DEk&utm_campaign=designshare&utm_medium=link&utm_source=publishpresent

Exemplos: https://github.com/ThiagoL29/Semin-rio-Bootstrap

**Comment by jemaf** [comment]
* Motivação bem apresentada
* Bons exemplos!

Nota: 100%
