### ISSUE TITLE
Entrega - tema: barra de navegação

### ISSUE THREAD

**Issue by guilherme-dnz** [COLTEC-DAW/Seminarios-Frameworks-CSS#23]
Slide:
https://www.canva.com/design/DAFBefaJhYk/XWcbiH0Tt2QlVwHGraj4Tg/edit?utm_content=DAFBefaJhYk&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

Código:
https://github.com/guilherme-dnz/Semin-rio-Daw.git

**Comment by jemaf** [comment]
+ Bons exemplos!
+ Boa motivação!
- O exemplo de código poderia ser um pouco mais elaborado (explorando mais os sub-componentes)

Nota: 90%
