### ISSUE TITLE
Entrega do Seminário de Frameworks

### ISSUE THREAD

**Issue by LuaVitor** [COLTEC-DAW/Seminarios-Frameworks-CSS#24]
Tema: Input do Usuário (Forms e Buttons)
Grupo: Enzo Bigodeiro, Luan Vitor, Lucas Gomes, Luiza Moselli

Arquivos: https://github.com/LuaVitor/E08-Seminarios-Framework

**Comment by jemaf** [comment]
- Apresentação simples em alguns aspectos
- Faltou mostrar exemplos e mais casos dos inputs

Nota: 75%
