### ISSUE TITLE
Entrega do tópico de Imagens e Media.

### ISSUE THREAD

**Issue by Gabriel-R-Pereira** [COLTEC-DAW/Seminarios-Frameworks-CSS#25]
Integrantes: Bernardo Tavares e Gabriel Rodrigues.
Link para o código e slide: https://github.com/GabrielR03/Seminario-01-DAW
Apenas slide: https://www.canva.com/design/DAFBhiza-Jc/3PsIoEP27XnowKHrEgWNSQ/view?utm_content=DAFBhiza-Jc&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink

**Comment by jemaf** [comment]
* Boa apresentação! 
* Exemplos completos!
* Os slides poderiam ser um pouco mais legíveis

Nota: 90%
