### ISSUE TITLE
Entrega do grupo Revelando Conteúdo

### ISSUE THREAD

**Issue by fernandrade04** [COLTEC-DAW/Seminarios-Frameworks-CSS#26]
https://www.canva.com/design/DAFBiUE-a4E/MyJnI7mZlXGEg2r3iDydCA/view?utm_content=DAFBiUE-a4E&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by jemaf** [comment]
* Boa explicação sobre os componentes
* Os exemplos dos componentes foram interessantes

* Faltou uma demonstração dos componentes na prática (repositório com exemplo de código, etc)
* Penalidade por atraso na apresentação (-25%)

Nota: 65%
