### ISSUE TITLE
Grupos de Apresentação

### ISSUE THREAD

**Issue by jemaf** [COLTEC-DAW/Seminarios-Frameworks-CSS#5]
Dizer nos comentários os componentes do grupo e qual tema o grupo escolheu. Exemplo:

**Grupo 42**
* Batman
* Coringa

Tema: Carousel

**Comment by MariSantos17** [comment]
**Grupo 1**

- Italo
- João Gabriel
- Mariana

Tema: Carousel

**Comment by Veazey** [comment]
Grupo 2
-Gabriel Veazey
-Guilherme de Assis
-Mateus Bernardo

Tema: Tabs, Pills and Tabbed Navigation

**Comment by RitaRez** [comment]
**Grupo 3**
--> Dener Vieira
-->Henrique Anastácio
-->Rita Rezende

Tema: Revealing Content: Tooltips, Popovers and Modals

**Comment by gegen07** [comment]
Grupo 4
- Germano Barcelos
- Mathias Gonçalves
- Reinaldo Magalhães


Tema: Hide and Seek - Collapse, Accordion, Scrollspy and Affix

**Comment by ibryans** [comment]
Grupo 5

- Bryan Santos
- Gustavo Henrique

Tema: Alerting Users: Labels, Badges, Alerts, Progress Bars

**Comment by beromes** [comment]
Grupo 6

- Bernardo Nunes
- Willian Vítor

Tema: User input: buttons and forms

**Comment by joaovitorbraga** [comment]
Grupo 7 

- João Vitor Braga
- Caio Lelis 
- Artur Moura

 Tema: images and media: Images, Thumbnails, Media objects

**Comment by gustavo-depaula** [comment]
Grupo 8
* Gustavo de Paula 
* Raul F Mansur

Tema: Displaying contents: como foi parar no servidor as marcações feitas na mesa se o carrinho tava sem bateria, ein @jemaf

**Comment by raul4247** [comment]
Grupo 8
- Gustavo de Paula
- Raul F Mansur

Tema: Displaying contents: Pq o projeto mais toperson (_pakot_) não fechou o trabson, hein @jemaf

**Comment by jemaf** [comment]
@raul4247 o @gustavo-depaula provavelmente sabe a resposta 😬

**Comment by gustavo-depaula** [comment]
e o carrinho @jemaf
